// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelcomeScreen.API.Data;

#nullable disable

namespace WelcomeScreen.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301130923_AddLastPolledId")]
    partial class AddLastPolledId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WelcomeScreen.API.Models.DataSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ConnectionStringEncrypted");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LastPolledId")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TriggerColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WelcomeScreenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WelcomeScreenId")
                        .IsUnique();

                    b.ToTable("DataSources");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.EventField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimationDelay")
                        .HasColumnType("int");

                    b.Property<int>("AnimationDuration")
                        .HasColumnType("int");

                    b.Property<string>("AnimationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayLabel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("FontWeight")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionY")
                        .HasColumnType("float");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextAlign")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WelcomeScreenId")
                        .HasColumnType("int");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("WelcomeScreenId");

                    b.ToTable("EventFields");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WelcomeScreenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WelcomeScreenId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.ScreenConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BackgroundMediaId")
                        .HasColumnType("int");

                    b.Property<int>("CanvasHeight")
                        .HasColumnType("int");

                    b.Property<int>("CanvasWidth")
                        .HasColumnType("int");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("WelcomeScreenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundMediaId");

                    b.HasIndex("WelcomeScreenId")
                        .IsUnique();

                    b.ToTable("ScreenConfigs");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.WelcomeScreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WelcomeScreens");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.DataSource", b =>
                {
                    b.HasOne("WelcomeScreen.API.Models.WelcomeScreen", "WelcomeScreen")
                        .WithOne("DataSource")
                        .HasForeignKey("WelcomeScreen.API.Models.DataSource", "WelcomeScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WelcomeScreen");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.EventField", b =>
                {
                    b.HasOne("WelcomeScreen.API.Models.WelcomeScreen", "WelcomeScreen")
                        .WithMany("Fields")
                        .HasForeignKey("WelcomeScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WelcomeScreen");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.MediaFile", b =>
                {
                    b.HasOne("WelcomeScreen.API.Models.WelcomeScreen", "WelcomeScreen")
                        .WithMany()
                        .HasForeignKey("WelcomeScreenId");

                    b.Navigation("WelcomeScreen");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.ScreenConfig", b =>
                {
                    b.HasOne("WelcomeScreen.API.Models.MediaFile", "BackgroundMedia")
                        .WithMany()
                        .HasForeignKey("BackgroundMediaId");

                    b.HasOne("WelcomeScreen.API.Models.WelcomeScreen", "WelcomeScreen")
                        .WithOne("ScreenConfig")
                        .HasForeignKey("WelcomeScreen.API.Models.ScreenConfig", "WelcomeScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BackgroundMedia");

                    b.Navigation("WelcomeScreen");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.WelcomeScreen", b =>
                {
                    b.HasOne("WelcomeScreen.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WelcomeScreen.API.Models.WelcomeScreen", b =>
                {
                    b.Navigation("DataSource");

                    b.Navigation("Fields");

                    b.Navigation("ScreenConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
